version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s:%(funcName)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  simple:
    format: "%(asctime)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  json:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

filters:
  info_filter:
    (): utils.logging_filters.InfoFilter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  
  file_detailed:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/healthy-mcp.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  file_error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/healthy-mcp_error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  file_access:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: logs/healthy-mcp_access.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  file_debug:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/healthy-mcp_debug.log
    maxBytes: 52428800  # 50MB
    backupCount: 3
    encoding: utf8

loggers:
  "":  # Root logger
    level: INFO
    handlers: [console, file_detailed, file_error]
  
  uvicorn.access:
    level: INFO
    handlers: [file_access]
    propagate: false
  
  uvicorn.error:
    level: INFO
    handlers: [file_error]
    propagate: false
  
  fastapi:
    level: INFO
    handlers: [console, file_detailed]
    propagate: false
  
  websockets:
    level: WARNING
    handlers: [file_detailed]
    propagate: false
  
  sqlmodel:
    level: WARNING
    handlers: [file_detailed]
    propagate: false
  
  httpx:
    level: WARNING
    handlers: [file_detailed]
    propagate: false
  
  healthy-mcp:
    level: DEBUG
    handlers: [console, file_detailed, file_error, file_debug]
    propagate: false
  
  healthy-mcp.websocket:
    level: INFO
    handlers: [console, file_detailed, file_access]
    propagate: false
  
  healthy-mcp.database:
    level: INFO
    handlers: [file_detailed]
    propagate: false
  
  healthy-mcp.api:
    level: INFO
    handlers: [console, file_detailed, file_access]
    propagate: false